<x-app-layout>
    <x-slot name="title">Products</x-slot><x-slot name="pageTitle">Product master</x-slot><x-slot name="breadcrumb">Masters / Products</x-slot>
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h2 class="h5 mb-1">Products & equipment</h2><div class="small text-secondary">Manage HVAC equipment, warranty and service checklist mappings.</div></div><div class="d-flex gap-2"><button class="btn btn-light border" data-bs-toggle="modal" data-bs-target="#categoryModal"><i data-lucide="tags" style="width:17px"></i> Category</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal"><i data-lucide="plus" style="width:17px"></i> New product</button></div></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <section class="nx-card overflow-hidden"><div class="p-3 border-bottom"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search product, code or brand"></div><div class="col-auto"><button class="btn btn-outline-primary">Search</button></div></form></div><div class="table-responsive"><table class="table nx-table mb-0"><thead><tr><th class="ps-4">Product</th><th>Category</th><th>Brand / Model</th><th>Serial no.</th><th>Warranty</th><th>Checklist</th><th>Status</th><th></th></tr></thead><tbody>
        @forelse($products as $product)<tr><td class="ps-4"><div class="fw-semibold">{{ $product->name }}</div><small class="text-secondary">{{ $product->code }}</small></td><td>{{ $product->category?->name ?? '—' }}</td><td>{{ $product->brand ?: '—' }}<small class="d-block text-secondary">{{ $product->model }}</small></td><td>{{ $product->serial_no ?: '—' }}</td><td>{{ $product->warranty_months ? $product->warranty_months.' months' : '—' }}</td><td>{{ $product->checklist?->name ?? 'Not mapped' }}</td><td><span class="badge rounded-pill {{ $product->active ? 'badge-soft-success' : 'bg-light text-secondary' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span></td><td><form method="POST" action="{{ route('products.destroy', $product) }}" onsubmit="return confirm('Remove this product?')">@csrf @method('DELETE')<button class="btn btn-sm btn-link text-danger"><i data-lucide="trash-2" style="width:16px"></i></button></form></td></tr>
        @empty<tr><td colspan="8" class="text-center py-5 text-secondary">No products added yet.</td></tr>@endforelse
    </tbody></table></div>@if($products->hasPages())<div class="p-3 border-top">{{ $products->links() }}</div>@endif</section>

    <div class="modal fade" id="productModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="POST" action="{{ route('products.store') }}" class="modal-content">@csrf<div class="modal-header"><div><h5 class="modal-title">New product</h5><small class="text-secondary">Add equipment to the product master.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Product name *</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="product_category_id"><option value="">Select</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Brand</label><input class="form-control" name="brand"></div><div class="col-md-4"><label class="form-label">Model</label><input class="form-control" name="model"></div><div class="col-md-4"><label class="form-label">Serial number</label><input class="form-control" name="serial_no"></div><div class="col-md-6"><label class="form-label">Service checklist</label><select class="form-select" name="service_checklist_id"><option value="">Not mapped</option>@foreach($checklists as $checklist)<option value="{{ $checklist->id }}">{{ $checklist->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Warranty months</label><input type="number" class="form-control" name="warranty_months" min="0"></div><div class="col-12"><label class="form-label">Specifications</label><textarea class="form-control" name="specifications_text" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create product</button></div></form></div></div>
    <div class="modal fade" id="categoryModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('product-categories.store') }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">New product category</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Category name *</label><input class="form-control" name="name" required></div><div class="modal-footer"><button class="btn btn-primary">Save category</button></div></form></div></div>
</x-app-layout>
