<x-app-layout>
    <x-slot name="title">{{ $employee ? 'Edit Employee' : 'New Employee' }}</x-slot><x-slot name="pageTitle">{{ $employee ? 'Edit employee' : 'Create employee' }}</x-slot><x-slot name="breadcrumb">HR / Employees / {{ $employee ? 'Edit' : 'New' }}</x-slot>
    @php
        $v = fn($key,$default='') => old($key, data_get($profile,$key,$default));
        $u = fn($key,$default='') => old($key, data_get($employee,$key,$default));
        $role = old('role', $employee?->getRoleNames()->first());
        $selectedPremises = old('premises', $employee?->premises?->pluck('id')->all() ?? []);
        $sections = ['Identity','Contact','Employment','Verification','Compensation','Benefits','Skills & Safety','Assets & Exit'];
        $langs = old('languages', $profile?->languages ?? []);
    @endphp
    @if($errors->any())<div class="alert alert-danger"><strong>Please fix the highlighted fields.</strong><div class="small">The first step with an error opens automatically.</div></div>@endif
    <form id="employeeWizard" method="POST" enctype="multipart/form-data" action="{{ $employee ? route('employees.update',$employee) : route('employees.store') }}" novalidate>@csrf @if($employee)@method('PUT')@endif
        <section class="nx-card p-3 p-lg-4 mb-4"><div class="nx-stepper">@foreach($sections as $i=>$label)<button class="nx-step {{ $i===0?'active':'' }}" type="button" data-step="{{ $i+1 }}"><span class="nx-step-number">{{ $i+1 }}</span><span>{{ $label }}</span></button>@endforeach</div></section>
        <section class="nx-card p-3 p-lg-4">
            <div class="nx-step-pane active" data-pane="1"><h2 class="nx-section-title">Core identity</h2><p class="small text-secondary">Personal identity and language details from Employee Master.</p><div class="row g-3">
                <div class="col-md-2"><label class="form-label">Salutation</label><select class="form-select" name="salutation"><option></option>@foreach(['Mr','Mrs','Miss','Dr'] as $x)<option @selected($v('salutation')===$x)>{{ $x }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">First name *</label><input class="form-control" name="first_name" value="{{ old('first_name',$profile?->first_name) }}" required></div><div class="col-md-3"><label class="form-label">Middle name</label><input class="form-control" name="middle_name" value="{{ $v('middle_name') }}"></div><div class="col-md-3"><label class="form-label">Last name</label><input class="form-control" name="last_name" value="{{ $v('last_name') }}"></div>
                <div class="col-md-4"><label class="form-label">Name in local script</label><input class="form-control" name="local_script_name" value="{{ $v('local_script_name') }}"></div><div class="col-md-3"><label class="form-label">Gender</label><select class="form-select" name="gender"><option></option>@foreach(['male','female','transgender','other'] as $x)<option value="{{ $x }}" @selected($v('gender')===$x)>{{ str($x)->headline() }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Date of birth</label><input type="date" class="form-control" name="date_of_birth" value="{{ $v('date_of_birth') }}"></div><div class="col-md-2"><label class="form-label">Blood group</label><input class="form-control" name="blood_group" value="{{ $v('blood_group') }}"></div>
                <div class="col-md-3"><label class="form-label">Marital status</label><select class="form-select" name="marital_status"><option></option>@foreach(['married','unmarried','other'] as $x)<option @selected($v('marital_status')===$x)>{{ $x }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Anniversary</label><input type="date" class="form-control" name="anniversary_date" value="{{ $v('anniversary_date') }}"></div><div class="col-md-3"><label class="form-label">Nationality</label><input class="form-control" name="nationality" value="{{ $v('nationality','Indian') }}"></div><div class="col-md-3"><label class="form-label">Religion</label><input class="form-control" name="religion" value="{{ $v('religion') }}"></div>
                <div class="col-md-8"><label class="form-label">Languages</label><div class="d-flex flex-wrap gap-2">@foreach(['English','Hindi','Marathi','Gujarati','Tamil','Telugu','Kannada','Malayalam','Bengali','Punjabi'] as $x)<label class="nx-choice"><input type="checkbox" name="languages[]" value="{{ $x }}" @checked(in_array($x,$langs))><span>{{ $x }}</span></label>@endforeach</div></div><div class="col-md-4"><label class="form-label">Profile picture</label><input type="file" class="form-control" name="profile_picture" accept="image/*"></div>
            </div></div>
            <div class="nx-step-pane" data-pane="2"><h2 class="nx-section-title">Contact, address & family</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Work email *</label><input type="email" class="form-control" name="work_email" value="{{ old('work_email',$employee?->email) }}" required></div><div class="col-md-4"><label class="form-label">Personal email</label><input type="email" class="form-control" name="personal_email" value="{{ $v('personal_email') }}"></div><div class="col-md-4"><label class="form-label">Mobile *</label><input class="form-control" name="phone" value="{{ $u('phone') }}" required></div>
                @foreach(['current_address'=>'Current address','permanent_address'=>'Permanent address','company_accommodation_address'=>'Company accommodation'] as $key=>$label)<div class="col-12"><div class="nx-repeat-card"><strong>{{ $label }}</strong><div class="row g-2 mt-1"><div class="col-md-6"><input class="form-control" name="{{ $key }}[line1]" value="{{ old($key.'.line1',data_get($profile,$key.'.line1')) }}" placeholder="Address line"></div><div class="col-md-3"><input class="form-control" name="{{ $key }}[city]" value="{{ old($key.'.city',data_get($profile,$key.'.city')) }}" placeholder="City"></div><div class="col-md-3"><input class="form-control" name="{{ $key }}[pin]" value="{{ old($key.'.pin',data_get($profile,$key.'.pin')) }}" placeholder="PIN"></div></div></div></div>@endforeach
                <div class="col-md-4"><label class="form-label">Emergency contact</label><input class="form-control" name="emergency_family[emergency_name]" value="{{ old('emergency_family.emergency_name',data_get($profile,'emergency_family.emergency_name')) }}"></div><div class="col-md-4"><label class="form-label">Relation</label><input class="form-control" name="emergency_family[relation]" value="{{ old('emergency_family.relation',data_get($profile,'emergency_family.relation')) }}"></div><div class="col-md-4"><label class="form-label">Emergency mobile</label><input class="form-control" name="emergency_family[mobile]" value="{{ old('emergency_family.mobile',data_get($profile,'emergency_family.mobile')) }}"></div>
            </div></div>
            <div class="nx-step-pane" data-pane="3"><h2 class="nx-section-title">Employment & user access</h2><div class="row g-3"><div class="col-md-3"><label class="form-label">Employee code</label><input class="form-control" name="employee_code" value="{{ $u('employee_code') }}" placeholder="Auto generated"></div><div class="col-md-3"><label class="form-label">Joining date</label><input type="date" class="form-control" name="date_of_joining" value="{{ $v('date_of_joining') }}"></div><div class="col-md-3"><label class="form-label">Employment type</label><select class="form-select" name="employment_type">@foreach(['permanent','probation','contract','intern','consultant'] as $x)<option value="{{ $x }}" @selected($v('employment_type','permanent')===$x)>{{ str($x)->headline() }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Category</label><input class="form-control" name="employee_category" value="{{ $v('employee_category') }}"></div>
                <div class="col-md-4"><label class="form-label">Department *</label><input class="form-control" name="department" value="{{ $u('department') }}" required></div><div class="col-md-4"><label class="form-label">Designation *</label><input class="form-control" name="designation" value="{{ $u('designation') }}" required></div><div class="col-md-2"><label class="form-label">Job grade</label><input class="form-control" name="job_grade" value="{{ $v('job_grade') }}"></div><div class="col-md-2"><label class="form-label">Status *</label><select class="form-select" name="user_status">@foreach(['active','inactive','on_leave','suspended'] as $x)<option value="{{ $x }}" @selected($u('status','active')===$x)>{{ str($x)->headline() }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="form-label">Role *</label><select class="form-select" name="role" required><option value="">Select role</option>@foreach($roles as $x)<option value="{{ $x->name }}" @selected($role===$x->name)>{{ $x->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Reporting manager</label><select class="form-select" name="reporting_manager_id"><option value="">None</option>@foreach($managers as $x)<option value="{{ $x->id }}" @selected($v('reporting_manager_id')==$x->id)>{{ $x->name }} · {{ $x->employee_code }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Assigned premises *</label><select class="form-select" name="premises[]" multiple size="4" required>@foreach($premises as $x)<option value="{{ $x->id }}" @selected(in_array($x->id,$selectedPremises))>{{ $x->name }}</option>@endforeach</select></div>
            </div></div>
            <div class="nx-step-pane" data-pane="4"><h2 class="nx-section-title">Identity & employee verification</h2><div class="row g-3">@foreach(['aadhaar'=>'Aadhaar','pan'=>'PAN','passport'=>'Passport','driving_licence'=>'Driving licence','voter_id'=>'Voter ID','uan'=>'UAN','esic'=>'ESIC','police_verification'=>'Police verification status','background_check'=>'Background check'] as $key=>$label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ in_array($key,['aadhaar','pan','passport','driving_licence','voter_id'])?'identity_documents':'verification' }}[{{ $key }}]" value="{{ old((in_array($key,['aadhaar','pan','passport','driving_licence','voter_id'])?'identity_documents':'verification').'.'.$key,data_get($profile,(in_array($key,['aadhaar','pan','passport','driving_licence','voter_id'])?'identity_documents':'verification').'.'.$key)) }}"></div>@endforeach<div class="col-12"><label class="form-label">Supporting documents</label><input type="file" class="form-control" name="documents[]" multiple></div></div></div>
            <div class="nx-step-pane" data-pane="5"><h2 class="nx-section-title">Compensation & payment</h2><div class="row g-3"><div class="col-md-3"><label class="form-label">Currency *</label><input class="form-control" name="salary_currency" value="{{ $v('salary_currency','INR') }}" required></div><div class="col-md-3"><label class="form-label">Frequency *</label><select class="form-select" name="pay_frequency">@foreach(['monthly','weekly','daily'] as $x)<option value="{{ $x }}" @selected($v('pay_frequency','monthly')===$x)>{{ ucfirst($x) }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Pay group</label><input class="form-control" name="pay_group" value="{{ $v('pay_group') }}"></div><div class="col-md-3"><label class="form-label">Gross monthly</label><input type="number" step=".01" class="form-control" name="gross_monthly_salary" value="{{ $v('gross_monthly_salary',0) }}"></div>@foreach(['basic_salary'=>'Basic salary','hra'=>'HRA','transport_allowance'=>'Transport','fuel_allowance'=>'Fuel','other_allowance'=>'Other allowance'] as $key=>$label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><input type="number" step=".01" min="0" class="form-control" name="{{ $key }}" value="{{ $v($key,0) }}"></div>@endforeach<div class="col-md-4"><label class="form-label">Bank name</label><input class="form-control" name="bank_details[bank_name]" value="{{ old('bank_details.bank_name',data_get($profile,'bank_details.bank_name')) }}"></div><div class="col-md-4"><label class="form-label">Account number</label><input class="form-control" name="bank_details[account_number]" value="{{ old('bank_details.account_number',data_get($profile,'bank_details.account_number')) }}"></div><div class="col-md-4"><label class="form-label">IFSC</label><input class="form-control" name="bank_details[ifsc]" value="{{ old('bank_details.ifsc',data_get($profile,'bank_details.ifsc')) }}"></div></div></div>
            <div class="nx-step-pane" data-pane="6"><h2 class="nx-section-title">Benefits, allowance & wellbeing</h2><div class="row g-3">@foreach(['pf_eligible'=>'PF eligible','esic_eligible'=>'ESIC eligible','insurance_policy'=>'Insurance policy','gratuity'=>'Gratuity','loan_balance'=>'Loan balance','bonus_plan'=>'Bonus plan','medical_benefit'=>'Medical benefit','meal_benefit'=>'Meal benefit'] as $key=>$label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><input class="form-control" name="benefits_allowances[{{ $key }}]" value="{{ old('benefits_allowances.'.$key,data_get($profile,'benefits_allowances.'.$key)) }}"></div>@endforeach<div class="col-md-6"><label class="form-label">Wellbeing notes</label><textarea class="form-control" name="engagement_wellbeing[notes]" rows="3">{{ old('engagement_wellbeing.notes',data_get($profile,'engagement_wellbeing.notes')) }}</textarea></div><div class="col-md-6"><label class="form-label">Employee remarks</label><textarea class="form-control" name="remarks" rows="3">{{ $v('remarks') }}</textarea></div></div></div>
            <div class="nx-step-pane" data-pane="7"><h2 class="nx-section-title">Education, skills, safety & performance</h2><div class="row g-3">@foreach(['highest_qualification'=>'Highest qualification','specialization'=>'Specialization','technical_skills'=>'Technical skills','certifications'=>'Certifications','trade_licence'=>'Trade licence','experience_years'=>'Experience years'] as $key=>$label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><input class="form-control" name="education_skills[{{ $key }}]" value="{{ old('education_skills.'.$key,data_get($profile,'education_skills.'.$key)) }}"></div>@endforeach @foreach(['ppe_size'=>'PPE size','safety_training'=>'Safety training','medical_fitness'=>'Medical fitness','incident_history'=>'Incident history'] as $key=>$label)<div class="col-md-3"><label class="form-label">{{ $label }}</label><input class="form-control" name="safety[{{ $key }}]" value="{{ old('safety.'.$key,data_get($profile,'safety.'.$key)) }}"></div>@endforeach<div class="col-md-6"><label class="form-label">Goals / KPI</label><textarea class="form-control" name="performance_career[kpi]">{{ old('performance_career.kpi',data_get($profile,'performance_career.kpi')) }}</textarea></div><div class="col-md-6"><label class="form-label">Career plan</label><textarea class="form-control" name="performance_career[career_plan]">{{ old('performance_career.career_plan',data_get($profile,'performance_career.career_plan')) }}</textarea></div></div></div>
            <div class="nx-step-pane" data-pane="8"><h2 class="nx-section-title">Assets, system access & separation</h2><div class="row g-3">@foreach(['laptop'=>'Laptop','mobile'=>'Company mobile','sim'=>'SIM','uniform'=>'Uniform issued','toolkit'=>'Toolkit','access_card'=>'Access card','email_access'=>'Email access','erp_access'=>'ERP access'] as $key=>$label)<div class="col-md-3"><label class="form-label">{{ $label }}</label><input class="form-control" name="assets_access[{{ $key }}]" value="{{ old('assets_access.'.$key,data_get($profile,'assets_access.'.$key)) }}"></div>@endforeach<div class="col-md-3"><label class="form-label">Resignation date</label><input type="date" class="form-control" name="exit_separation[resignation_date]" value="{{ old('exit_separation.resignation_date',data_get($profile,'exit_separation.resignation_date')) }}"></div><div class="col-md-3"><label class="form-label">Last working date</label><input type="date" class="form-control" name="exit_separation[last_working_date]" value="{{ old('exit_separation.last_working_date',data_get($profile,'exit_separation.last_working_date')) }}"></div><div class="col-md-6"><label class="form-label">Exit reason / clearance</label><textarea class="form-control" name="exit_separation[notes]">{{ old('exit_separation.notes',data_get($profile,'exit_separation.notes')) }}</textarea></div></div></div>
            <div class="nx-wizard-actions mt-4 pt-3 border-top"><button type="button" class="btn btn-outline-secondary" id="employeeBack"><i data-lucide="arrow-left" style="width:16px"></i>Back</button><div class="ms-auto d-flex gap-2"><a href="{{ route('employees.index') }}" class="btn btn-light border">Cancel</a><button type="button" class="btn btn-primary" id="employeeNext">Next <i data-lucide="arrow-right" style="width:16px"></i></button><button class="btn btn-success d-none" id="employeeSubmit">{{ $employee?'Save employee':'Create employee & user' }}</button></div></div>
        </section>
    </form>
    @push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('employeeWizard'),steps=[...document.querySelectorAll('.nx-step')],panes=[...document.querySelectorAll('.nx-step-pane')],back=document.getElementById('employeeBack'),next=document.getElementById('employeeNext'),submit=document.getElementById('employeeSubmit');let current=0;const errorNames=@json(array_keys($errors->toArray()));const map={first_name:0,work_email:1,phone:1,department:2,designation:2,role:2,premises:2,identity_documents:3,verification:3,basic_salary:4,bank_details:4,benefits_allowances:5,education_skills:6,safety:6,assets_access:7,exit_separation:7};if(errorNames.length){current=Math.min(...errorNames.map(x=>map[x.split('.')[0]]??0));errorNames.forEach(name=>{const el=form.querySelector(`[name="${name}"]`)||form.querySelector(`[name^="${name.split('.')[0]}["]`);el?.classList.add('is-invalid')});steps[current].classList.add('error')}function show(i){current=Math.max(0,Math.min(i,panes.length-1));panes.forEach((p,x)=>p.classList.toggle('active',x===current));steps.forEach((s,x)=>s.classList.toggle('active',x===current));back.disabled=current===0;next.classList.toggle('d-none',current===panes.length-1);submit.classList.toggle('d-none',current!==panes.length-1);window.scrollTo({top:0,behavior:'smooth'})}steps.forEach((s,i)=>s.onclick=()=>show(i));back.onclick=()=>show(current-1);next.onclick=()=>{const invalid=[...panes[current].querySelectorAll(':invalid')][0];if(invalid){invalid.reportValidity();invalid.classList.add('is-invalid');steps[current].classList.add('error');return}show(current+1)};show(current)});</script>@endpush
</x-app-layout>
