<x-app-layout>
    <x-slot name="title">Attendance</x-slot><x-slot name="pageTitle">Attendance management</x-slot><x-slot name="breadcrumb">Attendance / Today</x-slot>
    <div class="row g-3 mb-4"><div class="col-md-4"><div class="nx-card nx-metric"><div><div class="nx-metric-value">{{ $attendances->total() }}</div><div class="nx-metric-label">Records on {{ $date->format('d M') }}</div></div><span class="nx-metric-icon"><i data-lucide="users"></i></span></div></div><div class="col-md-4"><div class="nx-card nx-metric" style="--metric:#d97706;--metric-soft:#fef3c7"><div><div class="nx-metric-value">{{ $pendingCount }}</div><div class="nx-metric-label">Pending reviews</div></div><span class="nx-metric-icon"><i data-lucide="shield-question"></i></span></div></div><div class="col-md-4"><div class="nx-card nx-metric" style="--metric:#16a34a;--metric-soft:#dcfce7"><div><div class="nx-metric-value">{{ $activePremisesCount }}</div><div class="nx-metric-label">Active premises</div></div><span class="nx-metric-icon"><i data-lucide="map-pinned"></i></span></div></div></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <ul class="nav nav-pills gap-2 mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#records">Attendance records</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#premises">Premises & geofence</button></li></ul>
    <div class="tab-content"><div class="tab-pane fade show active" id="records"><section class="nx-card overflow-hidden"><div class="p-3 border-bottom"><form class="row g-2"><div class="col-md-3"><input type="date" class="form-control" name="date" value="{{ $date->format('Y-m-d') }}"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-outline-primary">Apply</button></div></form></div><div class="table-responsive"><table class="table nx-table mb-0"><thead><tr><th class="ps-4">Technician</th><th>Selfie</th><th>Premises</th><th>Check in / out</th><th>Distance</th><th>Location</th><th>Status</th><th>Review</th></tr></thead><tbody>
        @forelse($attendances as $attendance)<tr><td class="ps-4"><div class="fw-semibold">{{ $attendance->user->name }}</div><small class="text-secondary">{{ $attendance->user->employee_code }}</small></td><td><a href="{{ asset('storage/'.$attendance->selfie_path) }}" target="_blank"><img src="{{ asset('storage/'.$attendance->selfie_path) }}" alt="Selfie" width="46" height="46" class="rounded-3 object-fit-cover"></a></td><td>{{ $attendance->premises?->name ?? '—' }}</td><td><div>{{ $attendance->checked_in_at->format('h:i A') }}</div><small class="text-secondary">{{ $attendance->checked_out_at?->format('h:i A') ?? 'Not checked out' }}</small></td><td>{{ $attendance->distance_meters }} m</td><td><span class="badge rounded-pill {{ $attendance->inside_premises ? 'badge-soft-success' : 'badge-soft-danger' }}">{{ $attendance->inside_premises ? 'Inside' : 'Outside' }}</span></td><td><span class="badge rounded-pill {{ $attendance->status === 'approved' ? 'badge-soft-success' : ($attendance->status === 'rejected' ? 'badge-soft-danger' : 'badge-soft-warning') }}">{{ ucfirst($attendance->status) }}</span></td><td>@if($attendance->status === 'pending')<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#review{{ $attendance->id }}">Review</button>@else<span class="text-secondary small">Completed</span>@endif</td></tr>
        @empty<tr><td colspan="8" class="text-center py-5 text-secondary">No attendance records for this date.</td></tr>@endforelse
    </tbody></table></div>@if($attendances->hasPages())<div class="p-3">{{ $attendances->links() }}</div>@endif</section></div>
    <div class="tab-pane fade" id="premises">
        <div class="d-flex justify-content-end mb-3"><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#premisesModal"><i data-lucide="plus" style="width:17px"></i> New premises</button></div>
        <div class="row g-3">
            @forelse($premises as $place)
                @php
                    $editing = $errors->any() && (int) old('_premises_id') === $place->id;
                    $selectedTechnicians = $editing ? (old('technicians', $place->users->pluck('id')->all()) ?? []) : $place->users->pluck('id')->all();
                @endphp
                <div class="col-md-6 col-xl-4">
                    <article class="nx-card p-4 h-100">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="nx-metric-icon"><i data-lucide="map-pin"></i></span>
                            <div class="d-flex gap-2">
                                <span class="badge {{ $place->active ? 'badge-soft-success' : 'badge-soft-warning' }}">{{ $place->active ? 'Active' : 'Inactive' }}</span>
                                <span class="badge badge-soft-primary">{{ $place->radius_meters }} m radius</span>
                            </div>
                        </div>
                        <h3 class="h6 fw-bold mt-3 mb-1">{{ $place->name }}</h3>
                        <p class="small text-secondary mb-2">{{ $place->address ?: 'Address not set' }}</p>
                        <div class="small text-secondary mb-3">
                            <div>Coordinates: {{ $place->latitude }}, {{ $place->longitude }}</div>
                            <div>Shift: {{ $place->shift_start ? substr((string) $place->shift_start, 0, 5) : '—' }}–{{ $place->shift_end ? substr((string) $place->shift_end, 0, 5) : '—' }}</div>
                            <div>Technicians ({{ $place->users_count }}): {{ $place->users->pluck('name')->join(', ') ?: 'None assigned' }}</div>
                        </div>
                        <button class="btn btn-outline-primary btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#editPremises{{ $place->id }}" aria-expanded="{{ $editing ? 'true' : 'false' }}" aria-controls="editPremises{{ $place->id }}">
                            <i data-lucide="pencil" style="width:15px"></i> Edit premises
                        </button>
                        <div class="collapse {{ $editing ? 'show' : '' }} mt-3" id="editPremises{{ $place->id }}">
                            <form method="POST" action="{{ route('premises.update', $place) }}" class="border-top pt-3">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="_premises_id" value="{{ $place->id }}">
                                <div class="row g-3">
                                    <div class="col-12"><label class="form-label">Premises name *</label><input class="form-control" name="name" value="{{ $editing ? old('name', $place->name) : $place->name }}" required></div>
                                    <div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2">{{ $editing ? old('address', $place->address) : $place->address }}</textarea></div>
                                    <div class="col-md-6"><label class="form-label">Latitude *</label><input type="number" step="0.0000001" min="-90" max="90" class="form-control" name="latitude" value="{{ $editing ? old('latitude', $place->latitude) : $place->latitude }}" required></div>
                                    <div class="col-md-6"><label class="form-label">Longitude *</label><input type="number" step="0.0000001" min="-180" max="180" class="form-control" name="longitude" value="{{ $editing ? old('longitude', $place->longitude) : $place->longitude }}" required></div>
                                    <div class="col-12"><label class="form-label">Radius (meters) *</label><input type="number" class="form-control" name="radius_meters" value="{{ $editing ? old('radius_meters', $place->radius_meters) : $place->radius_meters }}" min="25" max="5000" required></div>
                                    <div class="col-md-6"><label class="form-label">Shift start</label><input type="time" class="form-control" name="shift_start" value="{{ $editing ? old('shift_start', $place->shift_start ? substr((string) $place->shift_start, 0, 5) : '') : ($place->shift_start ? substr((string) $place->shift_start, 0, 5) : '') }}"></div>
                                    <div class="col-md-6"><label class="form-label">Shift end</label><input type="time" class="form-control" name="shift_end" value="{{ $editing ? old('shift_end', $place->shift_end ? substr((string) $place->shift_end, 0, 5) : '') : ($place->shift_end ? substr((string) $place->shift_end, 0, 5) : '') }}"></div>
                                    <div class="col-12"><label class="form-label">Assign technicians</label><select class="form-select" name="technicians[]" multiple size="5">@foreach($technicians as $technician)<option value="{{ $technician->id }}" @selected(in_array($technician->id, $selectedTechnicians))>{{ $technician->name }} · {{ $technician->employee_code }}</option>@endforeach</select><div class="form-text">Use Ctrl or Command to select multiple technicians. Clear the selection to unassign everyone.</div></div>
                                    <div class="col-12">
                                        <input type="hidden" name="active" value="0">
                                        <label class="form-check form-switch"><input type="checkbox" class="form-check-input" name="active" value="1" @checked((bool) ($editing ? old('active', $place->active) : $place->active))><span class="form-check-label">Active for attendance</span></label>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-end gap-2 mt-3"><button type="button" class="btn btn-light btn-sm" data-bs-toggle="collapse" data-bs-target="#editPremises{{ $place->id }}">Cancel</button><button class="btn btn-primary btn-sm">Save changes</button></div>
                            </form>
                        </div>
                    </article>
                </div>
            @empty
                <div class="col-12"><div class="nx-card text-center py-5">No premises configured.</div></div>
            @endforelse
        </div>
    </div></div>
    @foreach($attendances as $attendance)@if($attendance->status === 'pending')<div class="modal fade" id="review{{ $attendance->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('attendance.review', $attendance) }}" class="modal-content">@csrf<div class="modal-header"><div><h5 class="modal-title">Review attendance</h5><small class="text-secondary">{{ $attendance->user->name }} · {{ $attendance->distance_meters }} m away</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-warning small">Technician marked attendance outside the configured geofence. Remark: {{ $attendance->remark ?: 'None' }}</div><label class="form-label">Decision *</label><select class="form-select mb-3" name="decision" required><option value="approved">Approve</option><option value="rejected">Reject</option></select><label class="form-label">Review remark *</label><textarea class="form-control" name="remark" rows="3" required></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save review</button></div></form></div></div>@endif @endforeach
    <div class="modal fade" id="premisesModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form method="POST" action="{{ route('premises.store') }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">New premises & geofence</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Premises name *</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Radius (meters) *</label><input type="number" class="form-control" name="radius_meters" value="200" min="25" required></div><div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2"></textarea></div><div class="col-md-6"><label class="form-label">Latitude *</label><input type="number" step="0.0000001" class="form-control" name="latitude" required></div><div class="col-md-6"><label class="form-label">Longitude *</label><input type="number" step="0.0000001" class="form-control" name="longitude" required></div><div class="col-md-6"><label class="form-label">Shift start</label><input type="time" class="form-control" name="shift_start" value="09:00"></div><div class="col-md-6"><label class="form-label">Shift end</label><input type="time" class="form-control" name="shift_end" value="18:00"></div><div class="col-12"><label class="form-label">Assign technicians</label><select class="form-select" name="technicians[]" multiple size="5">@foreach($technicians as $technician)<option value="{{ $technician->id }}">{{ $technician->name }} · {{ $technician->employee_code }}</option>@endforeach</select></div></div></div><div class="modal-footer"><button class="btn btn-primary">Create premises</button></div></form></div></div>
</x-app-layout>
