<x-app-layout>
    <x-slot name="title">Reports</x-slot><x-slot name="pageTitle">Reports & analytics</x-slot><x-slot name="breadcrumb">Reports / Overview</x-slot>
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="h5 mb-1">Operational analytics</h2><div class="small text-secondary">Attendance and task performance for the last 30 days.</div></div><button class="btn btn-light border" onclick="window.print()"><i data-lucide="download" style="width:17px"></i> Export PDF</button></div>
    @php $cards=[['Customers',$summary['customers'],'building-2'],['Technicians',$summary['technicians'],'users'],['Monthly check-ins',$summary['attendance'],'calendar-check'],['Task completion',$summary['completion'].'%','circle-check-big']]; @endphp
    <div class="row g-3 mb-4">@foreach($cards as [$label,$value,$icon])<div class="col-6 col-xl-3"><div class="nx-card nx-metric"><div><div class="nx-metric-value">{{ $value }}</div><div class="nx-metric-label">{{ $label }}</div></div><span class="nx-metric-icon"><i data-lucide="{{ $icon }}"></i></span></div></div>@endforeach</div>
    <div class="row g-4 mb-4"><div class="col-xl-8"><section class="nx-card p-4"><h3 class="h6 fw-bold mb-1">Attendance & task volume</h3><div class="small text-secondary mb-3">Daily activity across the last month</div><div id="operationsChart" style="min-height:330px"></div></section></div><div class="col-xl-4"><section class="nx-card p-4 h-100"><h3 class="h6 fw-bold mb-1">Task completion</h3><div class="small text-secondary mb-3">Overall workflow status</div><div id="completionChart" style="min-height:330px"></div></section></div></div>
    <section class="nx-card overflow-hidden"><div class="p-4 pb-2"><h3 class="h6 fw-bold mb-1">Technician summary</h3><div class="small text-secondary">Attendance records and assigned workload.</div></div><div class="table-responsive"><table class="table nx-table mb-0"><thead><tr><th class="ps-4">Technician</th><th>Department</th><th>Attendance records</th><th>Assigned tasks</th><th>Performance</th></tr></thead><tbody>@forelse($technicianStats as $technician)<tr><td class="ps-4"><div class="fw-semibold">{{ $technician->name }}</div><small class="text-secondary">{{ $technician->employee_code }}</small></td><td>{{ $technician->department ?: '—' }}</td><td>{{ $technician->attendances_count }}</td><td>{{ $technician->assigned_tasks_count }}</td><td><span class="badge badge-soft-success">Active</span></td></tr>@empty<tr><td colspan="5" class="text-center py-5 text-secondary">No technician data.</td></tr>@endforelse</tbody></table></div></section>
    @push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{new ApexCharts(document.querySelector('#operationsChart'),{chart:{type:'area',height:330,toolbar:{show:false},fontFamily:'Inter'},series:[{name:'Attendance',data:@json($attendanceSeries)},{name:'New tasks',data:@json($taskSeries)}],xaxis:{categories:@json($labels),labels:{show:false}},colors:['#2563eb','#0ea5e9'],stroke:{curve:'smooth',width:3},fill:{type:'gradient',gradient:{opacityFrom:.28,opacityTo:.03}},dataLabels:{enabled:false},grid:{borderColor:'#eef2f7',strokeDashArray:4}}).render();new ApexCharts(document.querySelector('#completionChart'),{chart:{type:'radialBar',height:330},series:[{{ $summary['completion'] }}],colors:['#16a34a'],plotOptions:{radialBar:{hollow:{size:'67%'},dataLabels:{name:{show:true,offsetY:22},value:{fontSize:'34px',fontWeight:700,offsetY:-14}}}},labels:['Completed']}).render();});</script>@endpush
</x-app-layout>
