<x-app-layout>
    <x-slot name="title">Service Masters</x-slot>
    <x-slot name="pageTitle">Service masters</x-slot>
    <x-slot name="breadcrumb">Masters / Service Management</x-slot>

    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div><h2 class="h5 mb-1">HVAC service configuration</h2><div class="small text-secondary">Master prices, inspection responses and technician quick-select options.</div></div>
        @can('checklists.update')<div class="d-flex flex-wrap gap-2"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#conditionModal">Condition</button><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#optionModal">Quick option</button><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#typeModal">Service type</button><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#catalogModal"><i data-lucide="plus" style="width:16px"></i> Catalog service</button></div>@endcan
    </div>
    @if($errors->any())<div class="alert alert-danger"><strong>Could not save master.</strong> {{ $errors->first() }}</div>@endif

    <section class="nx-card p-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="h6 fw-bold mb-1">Service catalog</h3><div class="small text-secondary">Backend-controlled rates used in estimates and service execution.</div></div><span class="badge badge-soft-primary">{{ $catalogItems->where('active', true)->count() }} active</span></div><div class="table-responsive"><table class="table nx-table align-middle"><thead><tr><th>Code / Service</th><th>Category</th><th>Equipment</th><th class="text-end">Price</th><th class="text-end">Tax</th><th>Status</th></tr></thead><tbody>@foreach($catalogItems as $item)<tr><td><div class="fw-semibold">{{ $item->name }}</div><div class="small text-secondary">{{ $item->code }}</div></td><td>{{ $item->category ?: 'General' }}</td><td>{{ $item->equipment_type ?: 'All' }}</td><td class="text-end">₹{{ number_format((float) $item->standard_price, 2) }}</td><td class="text-end">{{ number_format((float) $item->tax_percent, 2) }}%</td><td><form method="POST" action="{{ route('service-masters.toggle', ['group' => 'catalog', 'id' => $item->id]) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $item->active ? 'btn-success' : 'btn-light border' }}">{{ $item->active ? 'Active' : 'Inactive' }}</button></form></td></tr>@endforeach</tbody></table></div></section>

    <div class="row g-4 mb-4">
        <div class="col-xl-7"><section class="nx-card p-4 h-100"><div class="d-flex justify-content-between mb-3"><div><h3 class="h6 fw-bold mb-1">Service types</h3><div class="small text-secondary">Job classification, default value and expected duration.</div></div><span class="badge bg-light text-secondary">{{ $serviceTypes->count() }}</span></div><div class="table-responsive"><table class="table nx-table align-middle"><thead><tr><th>Service type</th><th class="text-end">Default</th><th>Duration</th><th>Status</th></tr></thead><tbody>@foreach($serviceTypes as $type)<tr><td><div class="fw-semibold">{{ $type->name }}</div><div class="small text-secondary">{{ $type->code }}</div></td><td class="text-end">₹{{ number_format((float) $type->default_price, 2) }}</td><td>{{ $type->estimated_minutes ? $type->estimated_minutes.' min' : '—' }}</td><td><form method="POST" action="{{ route('service-masters.toggle', ['group' => 'service-types', 'id' => $type->id]) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $type->active ? 'btn-success' : 'btn-light border' }}">{{ $type->active ? 'Active' : 'Inactive' }}</button></form></td></tr>@endforeach</tbody></table></div></section></div>
        <div class="col-xl-5"><section class="nx-card p-4 h-100"><div class="d-flex justify-content-between mb-3"><div><h3 class="h6 fw-bold mb-1">Inspection conditions</h3><div class="small text-secondary">Large tap choices shown to technicians.</div></div><span class="badge bg-light text-secondary">{{ $conditions->count() }}</span></div><div class="d-flex flex-column gap-2">@foreach($conditions as $condition)@php($class = match($condition->color) { 'success' => 'badge-soft-success', 'warning' => 'badge-soft-warning', 'danger' => 'badge-soft-danger', default => 'bg-light text-secondary' })<div class="d-flex align-items-center justify-content-between border rounded-3 p-2"><div><span class="badge {{ $class }}">{{ $condition->name }}</span><span class="small text-secondary ms-2">{{ $condition->is_issue ? 'Issue' : 'Normal' }}</span></div><form method="POST" action="{{ route('service-masters.toggle', ['group' => 'conditions', 'id' => $condition->id]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-link {{ $condition->active ? 'text-success' : 'text-secondary' }}">{{ $condition->active ? 'Active' : 'Inactive' }}</button></form></div>@endforeach</div></section></div>
    </div>

    <section class="nx-card p-4"><h3 class="h6 fw-bold mb-1">Technician quick options</h3><div class="small text-secondary mb-4">Payment methods, equipment types, reasons and units used in mobile forms.</div><div class="row g-4">@foreach($options as $type => $group)<div class="col-md-6 col-xl-4"><div class="small fw-bold text-uppercase text-secondary mb-2">{{ str($type)->replace('_', ' ') }}</div><div class="d-flex flex-wrap gap-2">@foreach($group as $option)<form method="POST" action="{{ route('service-masters.toggle', ['group' => 'options', 'id' => $option->id]) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $option->active ? 'btn-light border' : 'btn-outline-secondary text-decoration-line-through' }}">{{ $option->label }}</button></form>@endforeach</div></div>@endforeach</div></section>

    <div class="modal fade" id="typeModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('service-masters.service-types.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Add service type</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-4"><label class="form-label">Code *</label><input class="form-control" name="code" placeholder="ST-INSTALL" required></div><div class="col-8"><label class="form-label">Name *</label><input class="form-control" name="name" required></div><div class="col-6"><label class="form-label">Default price *</label><input type="number" step="0.01" min="0" class="form-control" name="default_price" value="0" required></div><div class="col-6"><label class="form-label">Tax % *</label><input type="number" step="0.01" min="0" max="100" class="form-control" name="tax_percent" value="18" required></div><div class="col-6"><label class="form-label">Estimated minutes</label><input type="number" min="1" class="form-control" name="estimated_minutes"></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="2"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save service type</button></div></form></div></div>

    <div class="modal fade" id="catalogModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('service-masters.catalog.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Add catalog service</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Code *</label><input class="form-control" name="code" placeholder="SVC-INSTALL" required></div><div class="col-md-8"><label class="form-label">Service name *</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Category</label><input class="form-control" name="category" placeholder="Installation"></div><div class="col-md-4"><label class="form-label">Equipment type</label><input class="form-control" name="equipment_type" placeholder="Split AC"></div><div class="col-md-4"><label class="form-label">Estimated minutes</label><input type="number" min="1" class="form-control" name="estimated_minutes"></div><div class="col-md-6"><label class="form-label">Standard price *</label><input type="number" step="0.01" min="0" class="form-control" name="standard_price" required></div><div class="col-md-6"><label class="form-label">Tax % *</label><input type="number" step="0.01" min="0" max="100" class="form-control" name="tax_percent" value="18" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save catalog service</button></div></form></div></div>

    <div class="modal fade" id="conditionModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('service-masters.conditions.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Add inspection condition</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-5"><label class="form-label">Code *</label><input class="form-control" name="code" placeholder="LOW_PRESSURE" required></div><div class="col-7"><label class="form-label">Label *</label><input class="form-control" name="name" required></div><div class="col-7"><label class="form-label">Colour</label><select class="form-select" name="color"><option value="success">Green</option><option value="warning">Yellow</option><option value="danger">Red</option><option value="secondary">Grey</option></select></div><div class="col-5 d-flex align-items-end"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_issue" value="1"><span class="form-check-label">Marks an issue</span></label></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save condition</button></div></form></div></div>

    <div class="modal fade" id="optionModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('service-masters.options.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Add quick option</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Option group *</label><select class="form-select" name="type" required><option value="equipment_type">Equipment Type</option><option value="ac_capacity">AC Capacity</option><option value="reschedule_reason">Reschedule Reason</option><option value="cancellation_reason">Cancellation Reason</option><option value="payment_method">Payment Method</option><option value="unit">Unit</option></select></div><div class="col-5"><label class="form-label">Code *</label><input class="form-control" name="code" required></div><div class="col-7"><label class="form-label">Label *</label><input class="form-control" name="label" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save option</button></div></form></div></div>
</x-app-layout>
