<x-app-layout>
    <x-slot name="title">{{ $serviceJob->job_no }}</x-slot>
    <x-slot name="pageTitle">{{ $serviceJob->job_no }}</x-slot>
    <x-slot name="breadcrumb">Service Jobs / {{ $serviceJob->job_no }}</x-slot>

    @php
        $stages = [
            ['Visit', ['assigned','contacted','confirmed','rescheduled','no_answer','on_the_way','arrived']],
            ['Inspect', ['inspection_in_progress','inspection_completed']],
            ['Approve', ['estimate_created','estimate_pending_approval','customer_approved']],
            ['Service', ['service_in_progress','service_completed']],
            ['Payment', ['payment_pending','partially_paid','paid']],
            ['Done', ['completed']],
        ];
        $currentStage = collect($stages)->search(fn ($stage) => in_array($serviceJob->status, $stage[1], true));
        $statusClass = match($serviceJob->status) { 'completed','paid','customer_approved' => 'badge-soft-success', 'cancelled','customer_declined' => 'badge-soft-danger', default => 'badge-soft-primary' };
        $paidAmount = (float) $serviceJob->payments->where('status', 'received')->sum('amount');
    @endphp
    <div class="d-flex flex-wrap align-items-start justify-content-between gap-3 mb-4">
        <div><a href="{{ route('service-jobs.index') }}" class="small d-inline-flex align-items-center gap-1 mb-2"><i data-lucide="arrow-left" style="width:15px"></i>Service jobs</a><h2 class="h5 mb-1">{{ $serviceJob->customer->name }}</h2><div class="text-secondary small">{{ $serviceJob->serviceType?->name ?? 'General service' }} · Assigned to {{ $serviceJob->technician->name }}</div></div>
        <div class="text-end"><div class="d-flex flex-wrap justify-content-end gap-2 mb-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('service-jobs.report', $serviceJob) }}"><i data-lucide="file-down" style="width:15px"></i> Service report</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('service-jobs.proforma', $serviceJob) }}"><i data-lucide="receipt-text" style="width:15px"></i> Proforma</a><span class="badge rounded-pill {{ $statusClass }} px-3 py-2">{{ $workflow->label($serviceJob->status) }}</span></div><div class="small text-secondary">Scheduled {{ $serviceJob->scheduled_at?->format('d M Y, h:i A') ?? '—' }}</div></div>
    </div>

    <section class="nx-card p-3 p-lg-4 mb-4">
        <div class="nx-service-progress">
            @foreach($stages as $index => [$label, $statuses])
                <div class="nx-service-stage {{ $currentStage !== false && $index < $currentStage ? 'done' : '' }} {{ $currentStage === $index ? 'active' : '' }}"><span>{{ $index + 1 }}</span><strong>{{ $label }}</strong></div>
            @endforeach
        </div>
    </section>

    <div class="row g-4">
        <div class="col-xl-8">
            <section class="nx-card p-4 mb-4"><div class="d-flex align-items-center gap-3 mb-4"><span class="nx-metric-icon"><i data-lucide="clipboard-list"></i></span><div><h3 class="h6 fw-bold mb-1">Job details</h3><div class="small text-secondary">Customer complaint and service location</div></div></div><div class="row g-4"><div class="col-md-6"><div class="small text-secondary">Complaint</div><div class="fw-semibold mt-1">{{ $serviceJob->complaint }}</div></div><div class="col-md-6"><div class="small text-secondary">Equipment</div><div class="fw-semibold mt-1">{{ collect([$serviceJob->equipment?->equipment_type, $serviceJob->equipment?->brand, $serviceJob->equipment?->model, $serviceJob->equipment?->capacity])->filter()->join(' · ') ?: 'Not linked' }}</div><div class="small text-secondary">{{ $serviceJob->equipment?->location }}</div></div><div class="col-md-6"><div class="small text-secondary">Address</div><div class="mt-1">{{ $serviceJob->service_address }}</div></div><div class="col-md-3"><div class="small text-secondary">Phone</div><a class="fw-semibold" href="tel:{{ $serviceJob->customer_phone }}">{{ $serviceJob->customer_phone }}</a></div><div class="col-md-3"><div class="small text-secondary">Priority</div><div class="fw-semibold">{{ str($serviceJob->priority)->headline() }}</div></div></div></section>

            <section class="nx-card p-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="h6 fw-bold mb-1">Work summary</h3><div class="small text-secondary">Inspection, services, materials and evidence</div></div><span class="badge badge-soft-primary">{{ $serviceJob->photos->count() }} photos</span></div><div class="row g-3"><div class="col-md-4"><div class="nx-review-box h-100"><div class="small text-secondary">Inspection</div><div class="h5 fw-bold mb-1">{{ $serviceJob->inspections->where('phase', 'pre')->first()?->items->whereNotNull('completed_at')->count() ?? 0 }}</div><div class="small">items checked</div></div></div><div class="col-md-4"><div class="nx-review-box h-100"><div class="small text-secondary">Services performed</div><div class="h5 fw-bold mb-1">{{ $serviceJob->performedServices->count() }}</div><div class="small">work items</div></div></div><div class="col-md-4"><div class="nx-review-box h-100"><div class="small text-secondary">Materials</div><div class="h5 fw-bold mb-1">{{ $serviceJob->materials->count() }}</div><div class="small">items consumed</div></div></div></div>@if($serviceJob->performedServices->isNotEmpty() || $serviceJob->materials->isNotEmpty())<div class="table-responsive mt-4"><table class="table nx-table"><thead><tr><th>Item</th><th>Type</th><th>Qty</th><th class="text-end">Amount</th></tr></thead><tbody>@foreach($serviceJob->performedServices as $service)<tr><td>{{ $service->name }}</td><td><span class="badge badge-soft-primary">Service</span></td><td>{{ $service->quantity }}</td><td class="text-end">₹{{ number_format((float) $service->line_total, 2) }}</td></tr>@endforeach @foreach($serviceJob->materials as $material)<tr><td>{{ $material->name }}</td><td><span class="badge badge-soft-warning">{{ $material->is_inventory ? 'Inventory' : 'Other material' }}</span></td><td>{{ $material->quantity }} {{ $material->unit }}</td><td class="text-end">₹{{ number_format((float) $material->line_total, 2) }}</td></tr>@endforeach</tbody></table></div>@endif</section>

            @if($serviceJob->inspections->isNotEmpty())<section class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-4">Inspection details</h3>@foreach($serviceJob->inspections as $inspection)<div class="fw-semibold mb-2">{{ $inspection->phase === 'pre' ? 'Pre-service inspection' : 'Post-service checklist' }} <span class="badge {{ $inspection->status === 'completed' ? 'badge-soft-success' : 'badge-soft-warning' }}">{{ str($inspection->status)->headline() }}</span></div><div class="table-responsive mb-4"><table class="table nx-table"><thead><tr><th>Check</th><th>Condition</th><th>Remark</th></tr></thead><tbody>@foreach($inspection->items as $item)<tr><td>{{ $item->label }}</td><td>{{ $item->condition?->name ?? 'Pending' }}</td><td>{{ $item->remark ?: '—' }}</td></tr>@endforeach</tbody></table></div>@endforeach</section>@endif

            @if($serviceJob->photos->isNotEmpty())<section class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-3">Service photos</h3><div class="row g-3">@foreach($serviceJob->photos as $photo)<div class="col-6 col-md-4"><a href="{{ asset('storage/'.$photo->path) }}" target="_blank" class="text-decoration-none"><img src="{{ asset('storage/'.$photo->path) }}" class="img-fluid rounded border w-100" style="height:150px;object-fit:cover" alt="{{ $photo->category }} service photo"><div class="small text-secondary mt-1 text-capitalize">{{ $photo->category }}{{ $photo->caption ? ' · '.$photo->caption : '' }}</div></a></div>@endforeach</div></section>@endif

            <section class="nx-card p-4"><h3 class="h6 fw-bold mb-4">Job timeline</h3><div class="nx-timeline">@foreach($serviceJob->statusHistory as $history)<div class="nx-timeline-item"><span class="nx-timeline-dot"></span><div class="d-flex flex-wrap justify-content-between gap-2"><div><div class="fw-semibold">{{ $workflow->label($history->to_status) }}</div><div class="small text-secondary">{{ $history->remark ?: $history->reason }}{{ $history->changedBy ? ' · '.$history->changedBy->name : '' }}</div></div><time class="small text-secondary">{{ $history->changed_at->format('d M, h:i A') }}</time></div></div>@endforeach</div></section>
        </div>
        <div class="col-xl-4">
            @can('service_jobs.assign')<aside class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-1">Assignment & schedule</h3><div class="small text-secondary mb-3">Changes are recorded in the job timeline.</div><form method="POST" action="{{ route('service-jobs.update', $serviceJob) }}" class="d-grid gap-3">@csrf @method('PUT')<div><label class="form-label">Technician</label><select class="form-select" name="assigned_to" required>@foreach($technicians as $technician)<option value="{{ $technician->id }}" @selected($serviceJob->assigned_to === $technician->id)>{{ $technician->name }}</option>@endforeach</select></div><div><label class="form-label">Scheduled date & time</label><input class="form-control" type="datetime-local" name="scheduled_at" value="{{ $serviceJob->scheduled_at?->format('Y-m-d\TH:i') }}" required></div><div><label class="form-label">Priority</label><select class="form-select" name="priority">@foreach(['normal','high','very_high','emergency'] as $priority)<option value="{{ $priority }}" @selected($serviceJob->priority === $priority)>{{ str($priority)->headline() }}</option>@endforeach</select></div><div><label class="form-label">Internal notes</label><textarea class="form-control" name="notes" rows="2">{{ $serviceJob->notes }}</textarea></div><button class="btn btn-primary" type="submit">Update assignment</button></form></aside>@endcan
            <aside class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-3">Financial summary</h3><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Estimate</span><strong>₹{{ number_format((float) ($serviceJob->estimates->first()?->final_amount ?? 0), 2) }}</strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Final amount</span><strong>₹{{ number_format((float) $serviceJob->final_amount, 2) }}</strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Received</span><strong class="text-success">₹{{ number_format($paidAmount, 2) }}</strong></div><div class="d-flex justify-content-between py-2"><span class="text-secondary">Pending</span><strong class="text-danger">₹{{ number_format(max(0, (float) $serviceJob->final_amount - $paidAmount), 2) }}</strong></div></aside>
            <aside class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-3">Service evidence</h3><div class="d-flex justify-content-between small py-2 border-bottom"><span class="text-secondary">Before photos</span><strong>{{ $serviceJob->photos->where('category', 'before')->count() }}</strong></div><div class="d-flex justify-content-between small py-2 border-bottom"><span class="text-secondary">During photos</span><strong>{{ $serviceJob->photos->where('category', 'during')->count() }}</strong></div><div class="d-flex justify-content-between small py-2 border-bottom"><span class="text-secondary">After photos</span><strong>{{ $serviceJob->photos->where('category', 'after')->count() }}</strong></div><div class="d-flex justify-content-between small py-2"><span class="text-secondary">Customer signatures</span><strong>{{ $serviceJob->signatures->count() }}</strong></div></aside>
            @if($serviceJob->estimates->isNotEmpty())<aside class="nx-card p-4 mb-4"><h3 class="h6 fw-bold mb-3">Customer approval</h3>@php($estimate = $serviceJob->estimates->first())<div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Estimate version</span><strong>#{{ $estimate->version }}</strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span class="text-secondary">Decision</span><strong>{{ str($estimate->status)->replace('_', ' ')->headline() }}</strong></div><div class="small text-secondary mt-3">{{ $estimate->customer_name ?: $estimate->decision_remark }}</div></aside>@endif
            @if($serviceJob->feedback)<aside class="nx-card p-4"><h3 class="h6 fw-bold mb-3">Customer feedback</h3>@if($serviceJob->feedback->submitted_at)<div class="h4 text-warning mb-1">{{ str_repeat('★', (int) $serviceJob->feedback->rating) }}<span class="text-secondary">{{ str_repeat('☆', 5 - (int) $serviceJob->feedback->rating) }}</span></div><div class="small mb-2">{{ $serviceJob->feedback->comments ?: 'No comments provided.' }}</div>@if($serviceJob->feedback->issue_still_exists || $serviceJob->feedback->request_callback)<div class="alert alert-warning py-2 small mb-0">{{ $serviceJob->feedback->issue_still_exists ? 'Issue still exists. ' : '' }}{{ $serviceJob->feedback->request_callback ? 'Callback requested.' : '' }}</div>@endif @else<div class="small text-secondary mb-2">Waiting for customer response.</div><a class="small" href="{{ route('service-feedback.show', $serviceJob->feedback->token) }}" target="_blank">Open feedback link</a>@endif</aside>@endif
        </div>
    </div>
</x-app-layout>
